"""empty message

Revision ID: 162588d2d980
Revises: 952b629a2403
Create Date: 2023-08-28 20:37:06.989091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162588d2d980'
down_revision = '952b629a2403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('species', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('species')
        batch_op.drop_column('height')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
