"""empty message

Revision ID: 934ffac8d339
Revises: 68f054c21c90
Create Date: 2023-09-02 14:10:59.246324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934ffac8d339'
down_revision = '68f054c21c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorite_user_id_key', ['user_id'])

    # ### end Alembic commands ###
