"""empty message

Revision ID: 952b629a2403
Revises: 676741fca682
Create Date: 2023-08-28 15:37:07.066788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952b629a2403'
down_revision = '676741fca682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
